
  SocialLogin:
  ################################
  # extension()->SocialLogin()の設定
  ################################
    ## ここをtrueにすると、リクエストごとにロードされ、オブジェクトが生成されます
    constant: false
    class:
      ## ファイルの実態
      resource: "<?php echo ENVI_BASE_DIR.'..'.DIRECTORY_SEPARATOR.'extensions'.DIRECTORY_SEPARATOR.'SocialLogin'.DIRECTORY_SEPARATOR;?>SocialLogin.php"
      ## クラス名
      class_name: "Envi\SocialLogin"
      ## シングルトン化するか
      singleton: true
    router:
      ## extensionの設定のパス
      resource: "<?php echo dirname(__FILE__).DIRECTORY_SEPARATOR.$app_name.'_SocialLogin.yml';?>"
